### ISSUE TITLE
Adding MLPAutoCompleteTextField to a view programitacally

### ISSUE THREAD

**Issue by patrick-fitzgerald** [EddyBorja/MLPAutoCompleteTextField#1]
Hi,
First of all thanks for a great plugin.
I'm using the example project and I've been trying to add the MLPAutoCompleteTextField to the MLPViewController programatically. 
I've deleted the view.xib file, but I cannot seem to get the custom text field to appear in the view programatically. Could you please advise how I can achieve this. I've included my viewDidLoad implementation below.
Thanks again,
Patrick

``` obj-c
- (void)viewDidLoad
{
    [super viewDidLoad];

    self.autocompleteTextField = [[MLPAutoCompleteTextField alloc] initWithFrame:CGRectMake(10, 200, 300, 40)];
    self.autocompleteTextField.delegate = self;
    self.autocompleteTextField.autoCompleteDataSource = self;
    self.autocompleteTextField.autoCompleteDelegate = self;


    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardDidShowWithNotification:) name:UIKeyboardDidShowNotification object:nil];

    [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardDidHideWithNotification:) name:UIKeyboardDidHideNotification object:nil];

    //Supported Styles:
    //[self.autocompleteTextField setBorderStyle:UITextBorderStyleBezel];
    //TODO[self.autocompleteTextField setBorderStyle:UITextBorderStyleLine];
    //[self.autocompleteTextField setBorderStyle:UITextBorderStyleNone];
    [self.autocompleteTextField setBorderStyle:UITextBorderStyleRoundedRect];


    //You can use custom TableViewCell classes and nibs in the autocomplete tableview if you wish.
    [self.autocompleteTextField registerAutoCompleteCellClass:[MLPCustomAutoCompleteCell class]
                                       forCellReuseIdentifier:@"CustomCellId"];

    [self.view addSubview:self.autocompleteTextField];


}
```

**Comment by harryhow** [comment]
@paddydub  Hi, I follow your code to use addSubview to create my view. The textfield appears but always having dataSource exception, I also noticed that there's a warning about assigning incompatible strong/weak to autoCompleteDataSource. Do you have any idea about this problem maybe causing dataStore expception? Thanks!
```
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An autocomplete datasource must implement either autoCompleteTextField:possibleCompletionsForString: or autoCompleteTextField:possibleCompletionsForString:completion
```
<img width="1077" alt="screen shot 2015-07-10 at 4 35 26 pm" src="https://cloud.githubusercontent.com/assets/693098/8628523/b9a789fe-2721-11e5-8431-3767bd4b0bff.png">

**Comment by hardikamal** [comment]
Hi @EddyBorja @harryhow Facing the same problem...any solution found???

**Comment by alenalexander** [comment]
Me too

**Comment by alenalexander** [comment]
Hey , 
I managed to found the solution as below. It was regarding the change in the syntax of Swift 3.0

func autoCompleteTextField(**_ textField**: MLPAutoCompleteTextField!, possibleCompletionsForString string: String!) -> [AnyObject]! 
{
    return myList as [AnyObject]!
}
