### ISSUE TITLE
Crash when typing too fast

### ISSUE THREAD

**Issue by logachu** [EddyBorja/MLPAutoCompleteTextField#45]
I'm testing on an iPad 1 running iOS 5.1.  There is a concurrency problem where a crash occurs in `MLPAutoCompleteFetchOperation` because `sentinelSemaphore` is signalled in `-[MLPAutoCompleteFetchOperation cancel]` while it is nil because it has never been created. 

If a `MLPAutoCompleteTextFieldDelegate` doesn't implement `autoCompleteTextField:possibleCompletionsForString:completionHandler:` then the semaphore will never be created in `-[MLPAutoCompleteFetchOperation main]`. Therefore if the user is typing fast enough that `fetchAutoCompleteSuggestions` gets called a second time while there is an operation on the queue, it will get cancelled which will call the operation's `cancel` method which attempts to signal the semaphore which was never created.

I suggest putting a guard to make sure the semaphore isn't nil in the -[MLPAutoCompleteFetchOperation cancel] method like so:

    - (void) cancel
    {
        if (sentinelSemaphore) dispatch_semaphore_signal(sentinelSemaphore);
        [super cancel];
    }

**Comment by Hummer101** [comment]
Does anyone has solved this issue? 
I can confirm this issue with an iPhone 4.

**Comment by logachu** [comment]
Hummer 101,

I put my solution at the end of the original bug report.

Barry
"Logachu"

**Comment by markshiz** [comment]
I have crash reports from Crashlytics verifying a crash here, but it reproduces sporadically --i.e., just typing fast in the emulator doesn't always do the trick.  I have `autoCompleteFetchRequestDelay` set to be `0.0f` which may also be related.

**Comment by markshiz** [comment]
Resolved by pull request #85
